INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('T-shirt Coton Bio', 76.34, 100, 'Vue/images/produit1.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Sweat Hoodie Bleu', 39.94, 41, 'Vue/images/produit2.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Casquette Stylée', 109.03, 16, 'Vue/images/produit3.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Jean Slim Noir', 59.54, 72, 'Vue/images/produit4.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Sac à dos urbain', 60.86, 50, 'Vue/images/produit5.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Montre Digitale', 143.63, 21, 'Vue/images/produit6.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Lunettes de soleil', 93.7, 61, 'Vue/images/produit7.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Chaussures Running', 78.19, 96, 'Vue/images/produit8.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Ceinture Cuir', 64.04, 31, 'Vue/images/produit9.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Gourde Inox', 99.54, 28, 'Vue/images/produit10.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Pantalon Chino', 149.27, 37, 'Vue/images/produit11.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Chemise Oxford', 129.47, 91, 'Vue/images/produit12.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Pull Cachemire', 144.29, 73, 'Vue/images/produit13.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Blouson Cuir', 27.35, 47, 'Vue/images/produit14.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Parka Hiver', 64.71, 28, 'Vue/images/produit15.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Short Sport', 128.7, 42, 'Vue/images/produit16.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Maillot de bain', 122.77, 53, 'Vue/images/produit17.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Chaussures en toile', 110.71, 81, 'Vue/images/produit18.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Bonnet Hiver', 25.12, 24, 'Vue/images/produit19.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Gants Cuir', 69.98, 30, 'Vue/images/produit20.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Polo Classique', 59.2, 29, 'Vue/images/produit21.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Mocassins', 35.31, 33, 'Vue/images/produit22.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Sandales Été', 130.12, 27, 'Vue/images/produit23.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Montre Sport', 135.93, 42, 'Vue/images/produit24.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Portefeuille Cuir', 73.59, 15, 'Vue/images/produit25.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Sac bandoulière', 43.07, 39, 'Vue/images/produit26.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Chapeau Panama', 15.8, 61, 'Vue/images/produit27.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Sweat à capuche', 93.31, 69, 'Vue/images/produit28.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Débardeur', 57.52, 38, 'Vue/images/produit29.png');
INSERT INTO produit (nom, prix, quantiteStock, image) VALUES ('Jean Droit', 134.53, 12, 'Vue/images/produit30.png');